### ISSUE TITLE
deploy docusaurus documentation with GitHub Pages

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/mAtches#131]
Hi @chuqyang 

We've created documentation for this repo in [docusaurus](docusaurus.io) and @vshioshvili and I are wondering if we could deploy it using GitHub Pages? The deploy for docusaurus creates the `gh-pages` ~~repo~~ branch with the documentation website: https://github.com/pepfar-datim/mAtches/tree/gh-pages, but an Admin user needs to turn this on under repo Settings:

![image](https://user-images.githubusercontent.com/18490902/112488698-15702980-8d7e-11eb-958e-45c77962baaf.png)

**Comment by chuqyang** [comment]
@tomzemp docusaurus creates the `gh-pages` _branch_ and not the _repo_ correct?

**Comment by tomzemp** [comment]
@chuqyang: Yes. Sorry. I meant branch, not repo

**Comment by chuqyang** [comment]
OK! Stand by!

**Comment by chuqyang** [comment]
Should be active!
![Screen Shot 2021-03-26 at 11 14 13 AM](https://user-images.githubusercontent.com/485602/112668721-75211000-8e24-11eb-9e20-841bed376bf0.png)

**Comment by tomzemp** [comment]
thank you @chuqyang (sorry for the delayed response here; there was something broken with my setup, that I had to fix and it took a while to get to that).

Now it looks like deployment at https://pepfar-datim.github.io/mAtches/ is working 🎉 
![image](https://user-images.githubusercontent.com/18490902/114566834-f1b04d00-9c72-11eb-9a00-01b181338b6b.png)

FYI @vshioshvili @FelixOngati (now deployed from /documentation directory from mAtches. I can't get both the actual deployment and the docusaurus `serve` script for testing static build to cooperate well, but this setup works with local testing and deployment
