### ISSUE TITLE
Documentation needs for Matches FHIR IG

### ISSUE THREAD

**Issue by maurya** [pepfar-datim/mAtches#138]
https://github.com/pepfar-datim/mAtches-ig
These are the basics for us to make the FHIR IG setup part self sufficient. 

- [x] 1. Documentation or link to how to setup HAPI FHIR
- [x] 2. How/where to run `bash _updatePublisher.sh` and `bash _genonce.sh`. What does this generate?
- [x] 3. Where/What are the generated resources by running the above scripts
- [x] 4. How can we load these generated resources into HAPI FHIR for making it ready for integration with a matches app
- [x] 5. Add this documentation into the matches README.

https://github.com/intrahealth/simple-hiv-ig covers a lot of this already but we need to trim it down to what is needed for this project.

**Comment by maurya** [comment]
@FelixOngati , @vshioshvili  any update on this?

**Comment by FelixOngati** [comment]
@maurya I have updated the matches-ig readme with setup information. 
Note that mAtches-IG scope is limited to explaining how to setup and run mAtches, and does not cover integration with FHIR, FHIR Resources and CQL, unlike the simple HIV IG [here](https://github.com/intrahealth/simple-hiv-ig).

**Comment by maurya** [comment]
@FelixOngati, Thank you for adding the setup information. 

I believe the requirement was for a completely new person to be able to set up and use the IG, which would need the documentation to integrate with FHIR and using the generated resources. Is there any other place those steps are being covered and can be linked in this document? Unless the person following the documentation is experienced working with FHIR and IG's, I don't think they will progress further than generating the resources.

@vshioshvili , please confirm if we need documentation for FHIR integration and usage.
